# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, conlist
from ansible.module_utils.appliance_api_client.models.config_system_resources_service_limit import ConfigSystemResourcesServiceLimit

class ConfigSystemResources(BaseModel):
    """
    Anapaya appliance system resources configuration.  # noqa: E501
    """
    service_limits: Optional[conlist(ConfigSystemResourcesServiceLimit)] = Field(None, description="Configuration for per service resource limits.")
    __properties = ["service_limits"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ConfigSystemResources:
        """Create an instance of ConfigSystemResources from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in service_limits (list)
        _items = []
        if self.service_limits:
            for _item in self.service_limits:
                if _item:
                    _items.append(_item.to_dict())
            _dict['service_limits'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ConfigSystemResources:
        """Create an instance of ConfigSystemResources from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ConfigSystemResources.parse_obj(obj)

        _obj = ConfigSystemResources.parse_obj({
            "service_limits": [ConfigSystemResourcesServiceLimit.from_dict(_item) for _item in obj.get("service_limits")] if obj.get("service_limits") is not None else None
        })
        return _obj


