# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, conint

class ConfigSCIONASNeighborInterfaceRemote(BaseModel):
    """
    Remote SCION interface endpoint of the link.  # noqa: E501
    """
    address: Optional[StrictStr] = Field(None, description="UDP/IP underlay endpoint of the SCION Interface. The data plane traffic is received on this address. The address must be specified as host:port. Both host and port must be specified.")
    interface_id: conint(strict=True, le=0, ge=1) = Field(..., description="SCION interface identifier. It must be unique in the SCION AS.")
    __properties = ["address", "interface_id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ConfigSCIONASNeighborInterfaceRemote:
        """Create an instance of ConfigSCIONASNeighborInterfaceRemote from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ConfigSCIONASNeighborInterfaceRemote:
        """Create an instance of ConfigSCIONASNeighborInterfaceRemote from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ConfigSCIONASNeighborInterfaceRemote.parse_obj(obj)

        _obj = ConfigSCIONASNeighborInterfaceRemote.parse_obj({
            "address": obj.get("address"),
            "interface_id": obj.get("interface_id")
        })
        return _obj


