# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr

class ConfigSCIONASControl(BaseModel):
    """
    The configuration for the SCION control service. The address configures where the control service is exposed. Clients connect to this address to request control plane data.  # noqa: E501
    """
    address: Optional[StrictStr] = Field(None, description="The address of the control service. The address must be specified as host:port. If the port is 0 it will be automatically allocated.")
    enabled: StrictBool = Field(..., description="Whether the service is enabled.")
    __properties = ["address", "enabled"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ConfigSCIONASControl:
        """Create an instance of ConfigSCIONASControl from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ConfigSCIONASControl:
        """Create an instance of ConfigSCIONASControl from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ConfigSCIONASControl.parse_obj(obj)

        _obj = ConfigSCIONASControl.parse_obj({
            "address": obj.get("address"),
            "enabled": obj.get("enabled")
        })
        return _obj


