# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt, StrictStr

class ConfigScionTunnelingDomainTrafficPolicyFailoverSequenceEntry(BaseModel):
    """
    The list of failover sequence entries, each of them associated with a path filter.  # noqa: E501
    """
    path_filter: StrictStr = Field(..., description="Name of the path filter associated with the failover sequence entry.")
    sequence_id: StrictInt = Field(..., description="Sequence number of the failover sequence entry. Sequence numbers define  the ordering of the items which turn detemines how the failover  between different path filters happens.")
    __properties = ["path_filter", "sequence_id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ConfigScionTunnelingDomainTrafficPolicyFailoverSequenceEntry:
        """Create an instance of ConfigScionTunnelingDomainTrafficPolicyFailoverSequenceEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ConfigScionTunnelingDomainTrafficPolicyFailoverSequenceEntry:
        """Create an instance of ConfigScionTunnelingDomainTrafficPolicyFailoverSequenceEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ConfigScionTunnelingDomainTrafficPolicyFailoverSequenceEntry.parse_obj(obj)

        _obj = ConfigScionTunnelingDomainTrafficPolicyFailoverSequenceEntry.parse_obj({
            "path_filter": obj.get("path_filter"),
            "sequence_id": obj.get("sequence_id")
        })
        return _obj


