# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist, validator
from ansible.module_utils.appliance_api_client.models.config_scionas_neighbor_interface import ConfigSCIONASNeighborInterface

class ConfigSCIONASNeighbor(BaseModel):
    """
    Neighbor SCION AS.  # noqa: E501
    """
    description: Optional[StrictStr] = Field(None, description="Description, or comment, for the neighbor AS.")
    interfaces: Optional[conlist(ConfigSCIONASNeighborInterface)] = Field(None, description="SCION interfaces on this device that link to the neighbor AS.")
    neighbor_isd_as: StrictStr = Field(..., description="ISD-AS number of the neighbor AS.")
    relationship: StrictStr = Field(..., description="The relationship to the neighbor AS. If the local AS is core, this value must either be CORE or CHILD. If the local is non-core, this value must either be PARENT, CHILD or PEER.")
    __properties = ["description", "interfaces", "neighbor_isd_as", "relationship"]

    @validator('relationship')
    def relationship_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('CORE', 'CHILD', 'PARENT', 'PEER'):
            raise ValueError("must be one of enum values ('CORE', 'CHILD', 'PARENT', 'PEER')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ConfigSCIONASNeighbor:
        """Create an instance of ConfigSCIONASNeighbor from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in interfaces (list)
        _items = []
        if self.interfaces:
            for _item in self.interfaces:
                if _item:
                    _items.append(_item.to_dict())
            _dict['interfaces'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ConfigSCIONASNeighbor:
        """Create an instance of ConfigSCIONASNeighbor from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ConfigSCIONASNeighbor.parse_obj(obj)

        _obj = ConfigSCIONASNeighbor.parse_obj({
            "description": obj.get("description"),
            "interfaces": [ConfigSCIONASNeighborInterface.from_dict(_item) for _item in obj.get("interfaces")] if obj.get("interfaces") is not None else None,
            "neighbor_isd_as": obj.get("neighbor_isd_as"),
            "relationship": obj.get("relationship")
        })
        return _obj


