# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictStr, conlist
from ansible.module_utils.appliance_api_client.models.debug_services_group import DebugServicesGroup

class DebugServicesResponseJson(BaseModel):
    """
    The list of services and service groups.  # noqa: E501
    """
    services: conlist(StrictStr) = Field(..., description="The list of services.")
    groups: conlist(DebugServicesGroup) = Field(..., description="The list of service groups.")
    __properties = ["services", "groups"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DebugServicesResponseJson:
        """Create an instance of DebugServicesResponseJson from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in groups (list)
        _items = []
        if self.groups:
            for _item in self.groups:
                if _item:
                    _items.append(_item.to_dict())
            _dict['groups'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DebugServicesResponseJson:
        """Create an instance of DebugServicesResponseJson from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DebugServicesResponseJson.parse_obj(obj)

        _obj = DebugServicesResponseJson.parse_obj({
            "services": obj.get("services"),
            "groups": [DebugServicesGroup.from_dict(_item) for _item in obj.get("groups")] if obj.get("groups") is not None else None
        })
        return _obj


