# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt, StrictStr

class DomainHasPathsToRemoteData(BaseModel):
    """
    Indicates the number of paths a domain has to a remote ISD-AS. If the domain has multiple ISD-AS, it could be that a path is not available for a certain ISD-AS pair, nonetheless, this is a condition to be aware of.   # noqa: E501
    """
    domain: StrictStr = Field(..., description="The name of the routing domain. ")
    local_isd_as: StrictStr = Field(..., description="The local ISD-AS in the domain. ")
    remote_isd_as: StrictStr = Field(..., description="The remote ISD-AS in the domain. ")
    paths: StrictInt = Field(..., description="The number of alive paths between the local and remote ISD-AS. ")
    __properties = ["domain", "local_isd_as", "remote_isd_as", "paths"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DomainHasPathsToRemoteData:
        """Create an instance of DomainHasPathsToRemoteData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DomainHasPathsToRemoteData:
        """Create an instance of DomainHasPathsToRemoteData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DomainHasPathsToRemoteData.parse_obj(obj)

        _obj = DomainHasPathsToRemoteData.parse_obj({
            "domain": obj.get("domain"),
            "local_isd_as": obj.get("local_isd_as"),
            "remote_isd_as": obj.get("remote_isd_as"),
            "paths": obj.get("paths")
        })
        return _obj


