# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel, StrictStr
from pydantic import Field
from ansible.module_utils.appliance_api_client.models.domain_remote_gateway import DomainRemoteGateway
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DomainHasReachableRemoteGatewaysData(BaseModel):
    """
    The list of remote Gateways in a domain that are reachable. 
    """ # noqa: E501
    domain: StrictStr = Field(description="The domain the remote gateways are part of. ")
    local_isd_as: StrictStr = Field(description="The local ISD-AS in the domain. ")
    remote_gateways: List[DomainRemoteGateway] = Field(description="The remote gateways in the domain. ")
    __properties: ClassVar[List[str]] = ["domain", "local_isd_as", "remote_gateways"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DomainHasReachableRemoteGatewaysData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in remote_gateways (list)
        _items = []
        if self.remote_gateways:
            for _item in self.remote_gateways:
                if _item:
                    _items.append(_item.to_dict())
            _dict['remote_gateways'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DomainHasReachableRemoteGatewaysData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "domain": obj.get("domain"),
            "local_isd_as": obj.get("local_isd_as"),
            "remote_gateways": [DomainRemoteGateway.from_dict(_item) for _item in obj.get("remote_gateways")] if obj.get("remote_gateways") is not None else None
        })
        return _obj


