# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictStr, conlist
from ansible.module_utils.appliance_api_client.models.domain_traffic_policy_failover_sequence import DomainTrafficPolicyFailoverSequence

class DomainTrafficPolicyHasPathsData(BaseModel):
    """
    The number of paths per failover sequence in a traffic policy in a domain.   # noqa: E501
    """
    domain: StrictStr = Field(..., description="The domain in which the traffic policy is. ")
    traffic_matcher: StrictStr = Field(..., description="The name of the traffic matcher that is being checked. ")
    failover_sequence: conlist(DomainTrafficPolicyFailoverSequence) = Field(..., description="The failover sequence that is being checked. ")
    __properties = ["domain", "traffic_matcher", "failover_sequence"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DomainTrafficPolicyHasPathsData:
        """Create an instance of DomainTrafficPolicyHasPathsData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in failover_sequence (list)
        _items = []
        if self.failover_sequence:
            for _item in self.failover_sequence:
                if _item:
                    _items.append(_item.to_dict())
            _dict['failover_sequence'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DomainTrafficPolicyHasPathsData:
        """Create an instance of DomainTrafficPolicyHasPathsData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DomainTrafficPolicyHasPathsData.parse_obj(obj)

        _obj = DomainTrafficPolicyHasPathsData.parse_obj({
            "domain": obj.get("domain"),
            "traffic_matcher": obj.get("traffic_matcher"),
            "failover_sequence": [DomainTrafficPolicyFailoverSequence.from_dict(_item) for _item in obj.get("failover_sequence")] if obj.get("failover_sequence") is not None else None
        })
        return _obj


