# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class FirewallTableFamily(str, Enum):
    """
    The table family of the nftables table.
    """

    """
    allowed enum values
    """
    IP = 'ip'
    IP6 = 'ip6'
    INET = 'inet'

    @classmethod
    def from_json(cls, json_str: str) -> FirewallTableFamily:
        """Create an instance of FirewallTableFamily from a JSON string"""
        return FirewallTableFamily(json.loads(json_str))


