# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime

from pydantic import BaseModel, Field, StrictStr
from ansible.module_utils.appliance_api_client.models.license_type import LicenseType
from ansible.module_utils.appliance_api_client.models.license_validity import LicenseValidity

class LicensePayloadJson(BaseModel):
    """
    LicensePayloadJson
    """
    license_id: StrictStr = Field(..., description="The license ID.")
    appliance_id: StrictStr = Field(..., description="The appliance ID for which the license is valid.")
    type: LicenseType = Field(...)
    issued: datetime = Field(..., description="The date and time when the license was issued.")
    validity: LicenseValidity = Field(...)
    __properties = ["license_id", "appliance_id", "type", "issued", "validity"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LicensePayloadJson:
        """Create an instance of LicensePayloadJson from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of type
        if self.type:
            _dict['type'] = self.type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of validity
        if self.validity:
            _dict['validity'] = self.validity.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LicensePayloadJson:
        """Create an instance of LicensePayloadJson from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LicensePayloadJson.parse_obj(obj)

        _obj = LicensePayloadJson.parse_obj({
            "license_id": obj.get("license_id"),
            "appliance_id": obj.get("appliance_id"),
            "type": LicenseType.from_dict(obj.get("type")) if obj.get("type") is not None else None,
            "issued": obj.get("issued"),
            "validity": LicenseValidity.from_dict(obj.get("validity")) if obj.get("validity") is not None else None
        })
        return _obj


