# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime

from pydantic import BaseModel, Field

class LicenseValidity(BaseModel):
    """
    LicenseValidity
    """
    effective_date: datetime = Field(..., description="The date and time when the license becomes valid.")
    final_date: datetime = Field(..., description="The date and time when the license expires.")
    __properties = ["effective_date", "final_date"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LicenseValidity:
        """Create an instance of LicenseValidity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LicenseValidity:
        """Create an instance of LicenseValidity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LicenseValidity.parse_obj(obj)

        _obj = LicenseValidity.parse_obj({
            "effective_date": obj.get("effective_date"),
            "final_date": obj.get("final_date")
        })
        return _obj


