# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist
from ansible.module_utils.appliance_api_client.models.network_interface import NetworkInterface

class NetworkInterfaces(BaseModel):
    """
    NetworkInterfaces
    """
    interfaces: conlist(NetworkInterface) = Field(...)
    __properties = ["interfaces"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> NetworkInterfaces:
        """Create an instance of NetworkInterfaces from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in interfaces (list)
        _items = []
        if self.interfaces:
            for _item in self.interfaces:
                if _item:
                    _items.append(_item.to_dict())
            _dict['interfaces'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> NetworkInterfaces:
        """Create an instance of NetworkInterfaces from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return NetworkInterfaces.parse_obj(obj)

        _obj = NetworkInterfaces.parse_obj({
            "interfaces": [NetworkInterface.from_dict(_item) for _item in obj.get("interfaces")] if obj.get("interfaces") is not None else None
        })
        return _obj


