# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: 0.1.0
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr, field_validator
from pydantic import Field
from typing_extensions import Annotated
from ansible.module_utils.appliance_api_client.models.hop import Hop
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Path(BaseModel):
    """
    Path
    """ # noqa: E501
    fingerprint: Annotated[str, Field(strict=True)] = Field(description="Hex-string representing the paths fingerprint.")
    hops: List[Hop]
    next_hop: StrictStr = Field(description="The internal UDP/IP underlay address of the SCION router that forwards traffic for this path. ")
    expiry: datetime = Field(description="Expiration time of the path.")
    mtu: Annotated[int, Field(strict=True, ge=0)] = Field(description="The maximum transmission unit in bytes for SCION packets. This represents the protocol data unit (PDU) of the SCION layer on this path.")
    latency: Optional[List[StrictStr]] = Field(default=None, description="Optional array of latency measurements between any two consecutive interfaces. Entry i describes the latency between interface i and i+1. ")
    status: Optional[StrictStr] = None
    local_ip: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["fingerprint", "hops", "next_hop", "expiry", "mtu", "latency", "status", "local_ip"]

    @field_validator('fingerprint')
    def fingerprint_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"[a-f0-9]+", value):
            raise ValueError(r"must validate the regular expression /[a-f0-9]+/")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('unknown', 'timeout', 'alive', 'scmp'):
            raise ValueError("must be one of enum values ('unknown', 'timeout', 'alive', 'scmp')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Path from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in hops (list)
        _items = []
        if self.hops:
            for _item in self.hops:
                if _item:
                    _items.append(_item.to_dict())
            _dict['hops'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Path from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fingerprint": obj.get("fingerprint"),
            "hops": [Hop.from_dict(_item) for _item in obj.get("hops")] if obj.get("hops") is not None else None,
            "next_hop": obj.get("next_hop"),
            "expiry": obj.get("expiry"),
            "mtu": obj.get("mtu"),
            "latency": obj.get("latency"),
            "status": obj.get("status"),
            "local_ip": obj.get("local_ip")
        })
        return _obj


