# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime

from pydantic import BaseModel, Field

class SchemasValidity(BaseModel):
    """
    SchemasValidity
    """
    not_before: datetime = Field(..., description="The time at which the validity period starts.")
    not_after: datetime = Field(..., description="The time at which the validity period stops.")
    __properties = ["not_before", "not_after"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SchemasValidity:
        """Create an instance of SchemasValidity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SchemasValidity:
        """Create an instance of SchemasValidity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SchemasValidity.parse_obj(obj)

        _obj = SchemasValidity.parse_obj({
            "not_before": obj.get("not_before"),
            "not_after": obj.get("not_after")
        })
        return _obj


