# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr, constr, validator

class ScionTunnelingIsdAsFilter(BaseModel):
    """
    ScionTunnelingIsdAsFilter
    """
    action: StrictStr = Field(..., description="An action for ISD-AS filtering.")
    isd_as: constr(strict=True) = Field(...)
    __properties = ["action", "isd_as"]

    @validator('action')
    def action_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('ACCEPT', 'REJECT'):
            raise ValueError("must be one of enum values ('ACCEPT', 'REJECT')")
        return value

    @validator('isd_as')
    def isd_as_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\d+-([a-f0-9]{1,4}:){2}([a-f0-9]{1,4})|\d+$", value):
            raise ValueError(r"must validate the regular expression /^\d+-([a-f0-9]{1,4}:){2}([a-f0-9]{1,4})|\d+$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ScionTunnelingIsdAsFilter:
        """Create an instance of ScionTunnelingIsdAsFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ScionTunnelingIsdAsFilter:
        """Create an instance of ScionTunnelingIsdAsFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ScionTunnelingIsdAsFilter.parse_obj(obj)

        _obj = ScionTunnelingIsdAsFilter.parse_obj({
            "action": obj.get("action"),
            "isd_as": obj.get("isd_as")
        })
        return _obj


