# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist

class ScionTunnelingFailoverSequenceEntry(BaseModel):
    """
    ScionTunnelingFailoverSequenceEntry
    """
    path_filter_name: StrictStr = Field(..., description="Name of the path filter used for this failover entry.")
    sessions: conlist(StrictStr) = Field(..., description="A list of session IDs used by this failover entry.")
    sessions_legacy: conlist(StrictInt) = Field(..., description="A list of session IDs used by this failover entry.")
    __properties = ["path_filter_name", "sessions", "sessions_legacy"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ScionTunnelingFailoverSequenceEntry:
        """Create an instance of ScionTunnelingFailoverSequenceEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ScionTunnelingFailoverSequenceEntry:
        """Create an instance of ScionTunnelingFailoverSequenceEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ScionTunnelingFailoverSequenceEntry.parse_obj(obj)

        _obj = ScionTunnelingFailoverSequenceEntry.parse_obj({
            "path_filter_name": obj.get("path_filter_name"),
            "sessions": obj.get("sessions"),
            "sessions_legacy": obj.get("sessions_legacy")
        })
        return _obj


