# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictStr, conlist
from ansible.module_utils.appliance_api_client.models.signature import Signature

class Signatures(BaseModel):
    """
    Signatures
    """
    name: StrictStr = Field(..., description="Name of the signed file")
    sha256sum: StrictStr = Field(..., description="SHA256 hash of the signed file")
    signatures: conlist(Signature) = Field(..., description="A list of signatures")
    __properties = ["name", "sha256sum", "signatures"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Signatures:
        """Create an instance of Signatures from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in signatures (list)
        _items = []
        if self.signatures:
            for _item in self.signatures:
                if _item:
                    _items.append(_item.to_dict())
            _dict['signatures'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Signatures:
        """Create an instance of Signatures from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Signatures.parse_obj(obj)

        _obj = Signatures.parse_obj({
            "name": obj.get("name"),
            "sha256sum": obj.get("sha256sum"),
            "signatures": [Signature.from_dict(_item) for _item in obj.get("signatures")] if obj.get("signatures") is not None else None
        })
        return _obj


