# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: 0.1.0
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.tools_scion_traceroute_post_request import ToolsScionTraceroutePostRequest

class TestToolsScionTraceroutePostRequest(unittest.TestCase):
    """ToolsScionTraceroutePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToolsScionTraceroutePostRequest:
        """Test ToolsScionTraceroutePostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToolsScionTraceroutePostRequest`
        """
        model = ToolsScionTraceroutePostRequest()
        if include_optional:
            return ToolsScionTraceroutePostRequest(
                run = openapi_client.models.traceroute_run.TracerouteRun(
                    destination_host = '', 
                    destination_isd_as = '1-ff00:0:110', 
                    source_isd_as = '1-ff00:0:110', 
                    sequence = '', 
                    timeout = '1s', 
                    probes_per_hop = 56, )
            )
        else:
            return ToolsScionTraceroutePostRequest(
                run = openapi_client.models.traceroute_run.TracerouteRun(
                    destination_host = '', 
                    destination_isd_as = '1-ff00:0:110', 
                    source_isd_as = '1-ff00:0:110', 
                    sequence = '', 
                    timeout = '1s', 
                    probes_per_hop = 56, ),
        )
        """

    def testToolsScionTraceroutePostRequest(self):
        """Test ToolsScionTraceroutePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
