# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: 0.1.0
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.domain_has_paths_to_remote import DomainHasPathsToRemote

class TestDomainHasPathsToRemote(unittest.TestCase):
    """DomainHasPathsToRemote unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DomainHasPathsToRemote:
        """Test DomainHasPathsToRemote
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DomainHasPathsToRemote`
        """
        model = DomainHasPathsToRemote()
        if include_optional:
            return DomainHasPathsToRemote(
                data = openapi_client.models.domain_has_paths_to_remote_data.DomainHasPathsToRemoteData(
                    domain = '', 
                    local_isd_as = '', 
                    remote_isd_as = '', 
                    paths = 56, )
            )
        else:
            return DomainHasPathsToRemote(
                data = openapi_client.models.domain_has_paths_to_remote_data.DomainHasPathsToRemoteData(
                    domain = '', 
                    local_isd_as = '', 
                    remote_isd_as = '', 
                    paths = 56, ),
        )
        """

    def testDomainHasPathsToRemote(self):
        """Test DomainHasPathsToRemote"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
