# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: 0.1.0
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.migrations_api import MigrationsApi


class TestMigrationsApi(unittest.TestCase):
    """MigrationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MigrationsApi()

    def tearDown(self) -> None:
        pass

    def test_migrations_config_get(self) -> None:
        """Test case for migrations_config_get

        Get the configuration for migration to {version}.
        """
        pass

    def test_migrations_config_put(self) -> None:
        """Test case for migrations_config_put

        Put the configuration for migration to {version}.
        """
        pass


if __name__ == '__main__':
    unittest.main()
