# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: 0.1.0
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.config_interfaces_ethernet_gateway import ConfigInterfacesEthernetGateway

class TestConfigInterfacesEthernetGateway(unittest.TestCase):
    """ConfigInterfacesEthernetGateway unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigInterfacesEthernetGateway:
        """Test ConfigInterfacesEthernetGateway
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigInterfacesEthernetGateway`
        """
        model = ConfigInterfacesEthernetGateway()
        if include_optional:
            return ConfigInterfacesEthernetGateway(
                ipv4_gateway = '',
                ipv6_gateway = ''
            )
        else:
            return ConfigInterfacesEthernetGateway(
        )
        """

    def testConfigInterfacesEthernetGateway(self):
        """Test ConfigInterfacesEthernetGateway"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
