# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: 0.1.0
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.config_interfaces_wireguard_route import ConfigInterfacesWireguardRoute

class TestConfigInterfacesWireguardRoute(unittest.TestCase):
    """ConfigInterfacesWireguardRoute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigInterfacesWireguardRoute:
        """Test ConfigInterfacesWireguardRoute
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigInterfacesWireguardRoute`
        """
        model = ConfigInterfacesWireguardRoute()
        if include_optional:
            return ConfigInterfacesWireguardRoute(
                comment = '',
                var_from = '',
                metric = 56,
                sequence_id = 3,
                to = '',
                via = ''
            )
        else:
            return ConfigInterfacesWireguardRoute(
                sequence_id = 3,
                to = '',
                via = '',
        )
        """

    def testConfigInterfacesWireguardRoute(self):
        """Test ConfigInterfacesWireguardRoute"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
