# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: 0.1.0
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.config_scion_tunneling_traffic_matcher import ConfigScionTunnelingTrafficMatcher

class TestConfigScionTunnelingTrafficMatcher(unittest.TestCase):
    """ConfigScionTunnelingTrafficMatcher unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigScionTunnelingTrafficMatcher:
        """Test ConfigScionTunnelingTrafficMatcher
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigScionTunnelingTrafficMatcher`
        """
        model = ConfigScionTunnelingTrafficMatcher()
        if include_optional:
            return ConfigScionTunnelingTrafficMatcher(
                condition = 'BOOL=true',
                description = ''all packets' matches all packets.',
                name = 'all packets'
            )
        else:
            return ConfigScionTunnelingTrafficMatcher(
                condition = 'BOOL=true',
                name = 'all packets',
        )
        """

    def testConfigScionTunnelingTrafficMatcher(self):
        """Test ConfigScionTunnelingTrafficMatcher"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
