# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: 0.1.0
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel, StrictInt, StrictStr, field_validator
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NetworkInterface(BaseModel):
    """
    Network interface summary.
    """ # noqa: E501
    name: StrictStr = Field(description="Name of the interface.")
    mtu: StrictInt = Field(description="MTU of the interface.")
    state: StrictStr = Field(description="State of the interface. Either up or down. Unknown means that the interface is in inconsistent state. ")
    driver: StrictStr = Field(description="Which networking stack (linux, vpp) the interface is part of.")
    addresses: List[StrictStr] = Field(description="IP addresses configured on the interface.")
    __properties: ClassVar[List[str]] = ["name", "mtu", "state", "driver", "addresses"]

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('up', 'down', 'unknown'):
            raise ValueError("must be one of enum values ('up', 'down', 'unknown')")
        return value

    @field_validator('driver')
    def driver_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('linux', 'vpp'):
            raise ValueError("must be one of enum values ('linux', 'vpp')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NetworkInterface from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NetworkInterface from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "mtu": obj.get("mtu"),
            "state": obj.get("state"),
            "driver": obj.get("driver"),
            "addresses": obj.get("addresses")
        })
        return _obj


