# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: 0.1.0
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel
from pydantic import Field
from openapi_client.models.scion_path_with_metrics import ScionPathWithMetrics
from openapi_client.models.scion_tunneling_routing_chain import ScionTunnelingRoutingChain
from openapi_client.models.scion_tunneling_session import ScionTunnelingSession
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ScionTunnelingSummary(BaseModel):
    """
    ScionTunnelingSummary
    """ # noqa: E501
    sessions: List[ScionTunnelingSession] = Field(description="A list of sessions. A session is a tunnel between two SCION appliances with a specific policy governing the selection of SCION paths. ")
    routing_chains: List[ScionTunnelingRoutingChain] = Field(description="A list of routing chains. A routing chain describes how outgoing IP packets are routed to different sessions. ")
    paths: Dict[str, ScionPathWithMetrics] = Field(description="A map of currently used SCION paths, indexed by path fingerprint.")
    __properties: ClassVar[List[str]] = ["sessions", "routing_chains", "paths"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ScionTunnelingSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sessions (list)
        _items = []
        if self.sessions:
            for _item in self.sessions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['sessions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in routing_chains (list)
        _items = []
        if self.routing_chains:
            for _item in self.routing_chains:
                if _item:
                    _items.append(_item.to_dict())
            _dict['routing_chains'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in paths (dict)
        _field_dict = {}
        if self.paths:
            for _key in self.paths:
                if self.paths[_key]:
                    _field_dict[_key] = self.paths[_key].to_dict()
            _dict['paths'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ScionTunnelingSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sessions": [ScionTunnelingSession.from_dict(_item) for _item in obj.get("sessions")] if obj.get("sessions") is not None else None,
            "routing_chains": [ScionTunnelingRoutingChain.from_dict(_item) for _item in obj.get("routing_chains")] if obj.get("routing_chains") is not None else None,
            "paths": dict(
                (_k, ScionPathWithMetrics.from_dict(_v))
                for _k, _v in obj.get("paths").items()
            )
            if obj.get("paths") is not None
            else None
        })
        return _obj


