# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from ansible.module_utils.appliance_api_client.models.config_interfaces_virtual_function_gateway import ConfigInterfacesVirtualFunctionGateway  # noqa: E501

class TestConfigInterfacesVirtualFunctionGateway(unittest.TestCase):
    """ConfigInterfacesVirtualFunctionGateway unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigInterfacesVirtualFunctionGateway:
        """Test ConfigInterfacesVirtualFunctionGateway
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigInterfacesVirtualFunctionGateway`
        """
        model = ConfigInterfacesVirtualFunctionGateway()  # noqa: E501
        if include_optional:
            return ConfigInterfacesVirtualFunctionGateway(
                ipv4_gateway = '',
                ipv6_gateway = ''
            )
        else:
            return ConfigInterfacesVirtualFunctionGateway(
        )
        """

    def testConfigInterfacesVirtualFunctionGateway(self):
        """Test ConfigInterfacesVirtualFunctionGateway"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
