# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ansible.module_utils.appliance_api_client.api.firewall_api import FirewallApi


class TestFirewallApi(unittest.TestCase):
    """FirewallApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FirewallApi()

    def tearDown(self) -> None:
        pass

    def test_firewall_chain_get(self) -> None:
        """Test case for firewall_chain_get

        Get the rules of a chain of a firewall table.
        """
        pass

    def test_firewall_default_post(self) -> None:
        """Test case for firewall_default_post

        Generate the default firewall configuration for the given appliance configuration.
        """
        pass

    def test_firewall_get(self) -> None:
        """Test case for firewall_get

        Get the firewall configuration of the appliance.
        """
        pass

    def test_firewall_table_get(self) -> None:
        """Test case for firewall_table_get

        Get a specific firewall table.
        """
        pass


if __name__ == '__main__':
    unittest.main()
