# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from ansible.module_utils.appliance_api_client.models.config_interfaces_ethernet_vrrp import ConfigInterfacesEthernetVrrp  # noqa: E501

class TestConfigInterfacesEthernetVrrp(unittest.TestCase):
    """ConfigInterfacesEthernetVrrp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigInterfacesEthernetVrrp:
        """Test ConfigInterfacesEthernetVrrp
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigInterfacesEthernetVrrp`
        """
        model = ConfigInterfacesEthernetVrrp()  # noqa: E501
        if include_optional:
            return ConfigInterfacesEthernetVrrp(
                addresses = [
                    ''
                    ],
                no_preempt = True,
                peers = [
                    ''
                    ],
                priority = 17,
                vrid = 3
            )
        else:
            return ConfigInterfacesEthernetVrrp(
                addresses = [
                    ''
                    ],
                peers = [
                    ''
                    ],
                vrid = 3,
        )
        """

    def testConfigInterfacesEthernetVrrp(self):
        """Test ConfigInterfacesEthernetVrrp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
