# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: 0.1.0
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from ansible.module_utils.appliance_api_client.models.signatures import Signatures

class TestSignatures(unittest.TestCase):
    """Signatures unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Signatures:
        """Test Signatures
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Signatures`
        """
        model = Signatures()
        if include_optional:
            return Signatures(
                name = '',
                sha256sum = '',
                signatures = [
                    ansible.module_utils.appliance_api_client.models.signature.Signature(
                        public_key = '', 
                        signature = '', 
                        creation_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return Signatures(
                name = '',
                sha256sum = '',
                signatures = [
                    ansible.module_utils.appliance_api_client.models.signature.Signature(
                        public_key = '', 
                        signature = '', 
                        creation_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testSignatures(self):
        """Test Signatures"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
