# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: 0.1.0
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from ansible.module_utils.appliance_api_client.models.fetch_status import FetchStatus

class TestFetchStatus(unittest.TestCase):
    """FetchStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFetchStatus(self):
        """Test FetchStatus"""
        # inst = FetchStatus()

if __name__ == '__main__':
    unittest.main()
