# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from ansible.module_utils.appliance_api_client.models.config_interfaces_wireguard import ConfigInterfacesWireguard  # noqa: E501

class TestConfigInterfacesWireguard(unittest.TestCase):
    """ConfigInterfacesWireguard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigInterfacesWireguard:
        """Test ConfigInterfacesWireguard
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigInterfacesWireguard`
        """
        model = ConfigInterfacesWireguard()  # noqa: E501
        if include_optional:
            return ConfigInterfacesWireguard(
                addresses = [
                    ''
                    ],
                gateway = ansible.module_utils.appliance_api_client.models.config_interfaces_wireguard_gateway.Config_Interfaces_Wireguard_Gateway(
                    ipv4_gateway = '', 
                    ipv6_gateway = '', ),
                mtu = 56,
                name = '',
                peers = [
                    ansible.module_utils.appliance_api_client.models.config_interfaces_wireguard_peer.Config_Interfaces_Wireguard_Peer(
                        allowed_ips = [
                            ''
                            ], 
                        endpoint = '', 
                        public_key = '', )
                    ],
                pointopoint = '',
                port = 56,
                routes = [
                    ansible.module_utils.appliance_api_client.models.config_interfaces_wireguard_route.Config_Interfaces_Wireguard_Route(
                        comment = '', 
                        from = '', 
                        metric = 56, 
                        sequence_id = 3, 
                        to = '', 
                        via = '', )
                    ]
            )
        else:
            return ConfigInterfacesWireguard(
                name = '',
                port = 56,
        )
        """

    def testConfigInterfacesWireguard(self):
        """Test ConfigInterfacesWireguard"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
