# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from ansible.module_utils.appliance_api_client.models.debug_cluster_peer import DebugClusterPeer  # noqa: E501

class TestDebugClusterPeer(unittest.TestCase):
    """DebugClusterPeer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DebugClusterPeer:
        """Test DebugClusterPeer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DebugClusterPeer`
        """
        model = DebugClusterPeer()  # noqa: E501
        if include_optional:
            return DebugClusterPeer(
                name = '',
                address = '',
                last_sync_attempt = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'success',
                error = ''
            )
        else:
            return DebugClusterPeer(
                name = '',
                address = '',
                last_sync_attempt = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'success',
        )
        """

    def testDebugClusterPeer(self):
        """Test DebugClusterPeer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
