# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from ansible.module_utils.appliance_api_client.models.config_scion_tunneling_path_filter import ConfigScionTunnelingPathFilter

class TestConfigScionTunnelingPathFilter(unittest.TestCase):
    """ConfigScionTunnelingPathFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigScionTunnelingPathFilter:
        """Test ConfigScionTunnelingPathFilter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigScionTunnelingPathFilter`
        """
        model = ConfigScionTunnelingPathFilter()
        if include_optional:
            return ConfigScionTunnelingPathFilter(
                acl = ["+ 64-0"],
                description = 'Match only paths in the Swiss Isolation Domain (ID 64).',
                hop_pattern = '0* 64+ 0+',
                name = 'CH ISD only'
            )
        else:
            return ConfigScionTunnelingPathFilter(
        )
        """

    def testConfigScionTunnelingPathFilter(self):
        """Test ConfigScionTunnelingPathFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
