# coding: utf-8

"""
    Appliance Management API

    Management API for the Anapaya EDGE, CORE and GATE appliances

    The version of the OpenAPI document: v0.37.1
    Contact: ops@anapaya.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from ansible.module_utils.appliance_api_client.models.service_type import ServiceType  # noqa: E501

class TestServiceType(unittest.TestCase):
    """ServiceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceType(self):
        """Test ServiceType"""
        # inst = ServiceType()

if __name__ == '__main__':
    unittest.main()
